name: urubu_do_pix_novo
version: 1.0.0+1

description: Um aplicativo Flutter para banco digital.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.9.0
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  share_plus: ^11.0.0
  intl: 0.20.2
  path: ^1.8.3
  pdf: ^3.10.8
  mask_text_input_formatter: ^2.9.0
  path_provider: ^2.1.3
  fl_chart: ^1.0.0  # Versão mais recente estável
  flutter_local_notifications: ^17.0.0  # Atualizado para a versão mais recente
  cached_network_image: ^3.4.1
  archive: ^3.4.10
  crypto: ^3.0.3
  device_info_plus: ^11.4.0  # Para obter informações do dispositivo
  connectivity_plus: ^5.0.2
  encrypt: ^5.0.3
  package_info_plus: ^8.3.0
  local_auth: ^2.2.0  # Para autenticação biométrica
  logging: ^1.2.0  # Para logging em produção

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf