name: urubu_pix
version: 1.0.0+1

description: Um aplicativo Flutter para banco digital.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.9.0
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  share_plus: ^11.0.0
  intl: ^0.19.0
  pdf: ^3.10.8
  mask_text_input_formatter: ^2.8.0
  path_provider: ^2.1.3
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf